瑞芯微机型增加用户预设置拨号功能

diff --git a/.github/workflows/build-rockchip-immortalWrt-24.10.yml b/.github/workflows/build-rockchip-immortalWrt-24.10.yml
--- a/.github/workflows/build-rockchip-immortalWrt-24.10.yml
+++ b/.github/workflows/build-rockchip-immortalWrt-24.10.yml
@@ -4,57 +4,73 @@ on:
   workflow_dispatch:
     inputs:
       profile:
+        type: choice
         description: |
-          输入 软路由型号（用逗号分隔的多个值），可选值如下：
-          ,ariaboard_photonicat
-          ,armsom_sige3
-          ,armsom_sige7
-          ,cyber_cyber3588-aib
-          ,ezpro_mrkaio-m68s
-          ,firefly_roc-rk3328-cc
-          ,firefly_roc-rk3568-pc
-          ,friendlyarm_nanopc-t4
-          ,friendlyarm_nanopc-t6
-          ,friendlyarm_nanopi-r2c
-          ,friendlyarm_nanopi-r2c-plus
-          ,friendlyarm_nanopi-r2s
-          ,friendlyarm_nanopi-r3s
-          ,friendlyarm_nanopi-r4s
-          ,friendlyarm_nanopi-r4se
-          ,friendlyarm_nanopi-r4s-enterprise
-          ,friendlyarm_nanopi-r5c
-          ,friendlyarm_nanopi-r5s
-          ,friendlyarm_nanopi-r6c
-          ,friendlyarm_nanopi-r6s
-          ,huake_guangmiao-g4c
-          ,lunzn_fastrhino-r66s
-          ,lunzn_fastrhino-r68s
-          ,lyt_t68m
-          ,pine64_rock64
-          ,pine64_rockpro64
-          ,radxa_cm3_io
-          ,radxa_e25
-          ,radxa_rock-3a
-          ,radxa_rock-3b
-          ,radxa_rock-3c
-          ,radxa_rock-5a
-          ,radxa_rock-5b
-          ,radxa_rock-pi-4a
-          ,radxa_rock-pi-e
-          ,radxa_rock-pi-s
-          ,radxa_zero-3e
-          ,radxa_zero-3w
-          ,sinovoip_bpi-r2-pro
-          ,xunlong_orangepi-5
-          ,xunlong_orangepi-5-plus
-          ,xunlong_orangepi-r1-plus
-          ,xunlong_orangepi-r1-plus-lts  
+          输入 软路由型号 可选值如下：
+        options:
+          - ariaboard_photonicat
+          - armsom_sige3
+          - armsom_sige7
+          - cyber_cyber3588-aib
+          - ezpro_mrkaio-m68s
+          - firefly_roc-rk3328-cc
+          - firefly_roc-rk3568-pc
+          - friendlyarm_nanopc-t4
+          - friendlyarm_nanopc-t6
+          - friendlyarm_nanopi-r2c
+          - friendlyarm_nanopi-r2c-plus
+          - friendlyarm_nanopi-r2s
+          - friendlyarm_nanopi-r3s
+          - friendlyarm_nanopi-r4s
+          - friendlyarm_nanopi-r4se
+          - friendlyarm_nanopi-r4s-enterprise
+          - friendlyarm_nanopi-r5c
+          - friendlyarm_nanopi-r5s
+          - friendlyarm_nanopi-r6c
+          - friendlyarm_nanopi-r6s
+          - huake_guangmiao-g4c
+          - lunzn_fastrhino-r66s
+          - lunzn_fastrhino-r68s
+          - lyt_t68m
+          - pine64_rock64
+          - pine64_rockpro64
+          - radxa_cm3_io
+          - radxa_e25
+          - radxa_rock-3a
+          - radxa_rock-3b
+          - radxa_rock-3c
+          - radxa_rock-5a
+          - radxa_rock-5b
+          - radxa_rock-pi-4a
+          - radxa_rock-pi-e
+          - radxa_rock-pi-s
+          - radxa_zero-3e
+          - radxa_zero-3w
+          - sinovoip_bpi-r2-pro
+          - xunlong_orangepi-5
+          - xunlong_orangepi-5-plus
+          - xunlong_orangepi-r1-plus
+          - xunlong_orangepi-r1-plus-lts
         required: true
         default: 'friendlyarm_nanopi-r3s'
       rootfs_partsize:
         description: '设置软件包大小 单位(MB)'
         required: true
         default: '1024'
+      enable_pppoe:
+        description: "是否配置PPPoE拨号信息?"
+        required: true
+        default: 'no'
+        type: choice
+        options:
+        - 'yes'
+        - 'no'
+      pppoe_account:
+        description: "宽带账号 (若启用PPPoE)"
+        required: false
+      pppoe_password:
+        description: "宽带密码 (若启用PPPoE)"
+        required: false
 
 jobs:
   build:
@@ -66,6 +82,15 @@ jobs:
 
       - name: Set executable permissions
         run: chmod +x ${{ github.workspace }}/rockchip/build.sh
+      
+      - name: Validate PPPoE Inputs
+        run: |
+          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
+            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
+              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
+              exit 1
+            fi
+          fi
 
       - name: Building Rockchip ImmortalWrt
         run: |
@@ -85,6 +110,9 @@ jobs:
               -v "${{ github.workspace }}/rockchip/build.sh:/home/build/immortalwrt/build.sh" \
               -e PROFILE=$profile \
               -e ROOTFS_PARTSIZE=$rootfs_partsize \
+              -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
+              -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
+              -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
               immortalwrt/imagebuilder:rockchip-armv8-openwrt-24.10.0-rc3 /bin/bash /home/build/immortalwrt/build.sh
           done
       - name: Generate Firmware SHA-256
