x86-64机型新增用户预设pppoe拨号功能

diff --git a/.github/workflows/build-x86-64-23.05.4.yml b/.github/workflows/build-x86-64-23.05.4.yml
--- a/.github/workflows/build-x86-64-23.05.4.yml
+++ b/.github/workflows/build-x86-64-23.05.4.yml
@@ -16,6 +16,20 @@ on:
         options:
           - 'yes'
           - 'no'
+      enable_pppoe:
+        description: "是否配置PPPoE拨号信息?"
+        required: true
+        default: 'no'
+        type: choice
+        options:
+        - 'yes'
+        - 'no'
+      pppoe_account:
+        description: "宽带账号 (若启用PPPoE)"
+        required: false
+      pppoe_password:
+        description: "宽带密码 (若启用PPPoE)"
+        required: false
 
 jobs:
   build:
@@ -27,6 +41,15 @@ jobs:
 
       - name: Set executable permissions
         run: chmod +x ${{ github.workspace }}/x86-64/build.sh
+      
+      - name: Validate PPPoE Inputs
+        run: |
+          if [[ "${{ inputs.enable_pppoe }}" == "yes" ]]; then
+            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
+              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
+              exit 1
+            fi
+          fi
 
       - name: Build ImmortalWrt-x86-64-eif
         run: |
@@ -46,6 +69,9 @@ jobs:
               -v "${{ github.workspace }}/x86-64/build.sh:/home/build/immortalwrt/build.sh" \
               -e PROFILE=$profile \
               -e INCLUDE_DOCKER=$include_docker \
+              -e ENABLE_PPPOE=${{ inputs.enable_pppoe }} \
+              -e PPPOE_ACCOUNT=${{ inputs.pppoe_account }} \
+              -e PPPOE_PASSWORD=${{ inputs.pppoe_password }} \
               immortalwrt/imagebuilder:x86-64-openwrt-23.05.4 /bin/bash /home/build/immortalwrt/build.sh
           done
       
